### ISSUE TITLE
Congrats guys!!! It took me years to find an approach to speech recog. on safari & chrome

### ISSUE THREAD

**Issue by inglesuniversal** [googlecreativelab/obvi#2]
Couple of questions...

1. How do you set up the auto language detection?

2. What is the maximum length it can capture voice?

3. How can I get the final value of the sentence captured instead of bits and pieces?

Thanks and AWESOME job to you all!!!!

**Comment by nick-jonas** [comment]
@inglesuniversal thanks Hugo, answers below:

**1. How do you set up the auto language detection?**

Auto language detection doesn't exist for speech recognition yet.  If you're referring to the ```autodetect``` property on the voice button, that refers to auto-detecting silence to stop listening for speech.

**2. What is the maximum length it can capture voice?**

If ```autodetect``` is set to false, it will listen continuously as long as the user is on a desktop browser (Web Speech API continuous mode has issues that have yet to be resolved on mobile devices).  I think it'll listen for up to ~60 seconds.

**3. How can I get the final value of the sentence captured instead of bits and pieces?**

```
obviElement.addEventListener('onSpeech', function(event){
    if(event.detail.isFinal){
        console.log('Speech response: ', event.detail.speechResult);
    }
})
```
